name: Build docker image

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '42 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build . --tag quay.io/aboutsource/wordpress:php7.4-apache
    - name: Login to quay.io
      run: echo ${{ secrets.QUAYIO_PASSWORD }} | docker login -u="${{ secrets.QUAYIO_USERNAME }}" --password-stdin quay.io
    - name: Push image
      run: docker push quay.io/aboutsource/wordpress:7.4-apache
